### PR TITLE
Support OVS style JSON encoding for empty Sets and Maps

### PR DESCRIPTION
**Pull request by roytman**
OVS encodes empty Sets and Maps as `["set",[]]` and `["map",[]]` respectively. 
However, the libovsdb and the default Golnag encoders creates something like `["set",null]` and `["map",null]`. If we try to
decode these valuse we get: `panic: interface conversion: interface {} is nil, not []interface {}`

This commit fixes it.

Signed-off-by: Alexey Roytman <roytman@il.ibm.com>

### CODE REVIEW

**Comment by amorenoz** [comment]
Hi @roytman, the PR makes sense to me but I'd like to ask a question: why do we need to encode an empty set if the default value for a set is an empty one? Isn't the same as not sending the field at all?

**Comment by roytman** [comment]
Hi @amorenoz , I'm trying to implement an OVSDB server with data stored in etcd, and would like to reuse your Json types. 
I understand that the library is mostly targeted client applications, so probably Json encoding is less relevant. 
OVSDB server sends empty sets and maps explicitly writing empty data, so I'm trying to be in line with it.

Another issue with the current implementation is that if you encode and after that decode an empty set/map you will get a `panic:` error.

**Comment by amorenoz** [comment]
@roytman sure, I agree the current implementation is wrong. I was curious because in some clients that use this library such as go-ovn, the empty values are just skipped, e.g: when we want to add a row with an empty map, we just omit the field. Thanks for the PR :)

BTW, I'd be interested in taking a look at your project. Is it open source?

**Comment by roytman** [comment]
@amorenoz 

>  I'd be interested in taking a look at your project. Is it open source?

Of course, you can see it, but we are in just at the start of the journey. https://github.com/IBM/ovsdb-etcd

I have 2 other questions: 

- In my fork I updated the `Set` marshal and unmarshal methods to provide OVSDB like behavior when the set contains a single entry. Can you consider including this functionality into the main stream ?
- Currently, the libovsdb supports only types from RFC7047, do you have plans to extend it by the types/methods from  https://docs.openvswitch.org/en/latest/ref/ovsdb-server.7/.

**Comment by amorenoz** [comment]
> I have 2 other questions:
> 
>     * In my fork I updated the `Set` marshal and unmarshal methods to provide OVSDB like behavior when the set contains a single entry. Can you consider including this functionality into the main stream ?
> 
In my PR I have considered that case: https://github.com/eBay/libovsdb/pull/31/commits/3156b528328b93ce432e752724910bf31c4587e2

>     * Currently, the libovsdb supports only types from RFC7047, do you have plans to extend it by the types/methods from  https://docs.openvswitch.org/en/latest/ref/ovsdb-server.7/.

I think we should add them, but maybe @vtolstov and @hzhou8 can comment?

**Comment by roytman** [comment]
> In my PR I have considered that case: 3156b52

The pointed commit does not belong to any branch on this repo, so I checked the latest code from #30 . 

`binding_test.go with the single string `"foo"` creates the correct ovsset object, but its json output is `["set",["foo"]]`, instead of `"foo"`
The code is able to transfer a single value into Set, but I believe that this transformation should be done by Set itself. if somebody wants to work on the low-level API with Sets and Maps...

And without this PR, the `Empty_String_Set` produces `["set",null]` instead of `["set",[]]`, the same with Maps

**Comment by vtolstov** [comment]
i think that adding types from https://docs.openvswitch.org/en/latest/ref/ovsdb-server.7/ will be good addition.

**Comment by amorenoz** [comment]
> > In my PR I have considered that case: [3156b52](https://github.com/eBay/libovsdb/commit/3156b528328b93ce432e752724910bf31c4587e2)
> 
> The pointed commit does not belong to any branch on this repo, so I checked the latest code from #30 .
> 
Sorry, I took it form an out-of-date tab :/

> `binding_test.go with the single string `"foo"`creates the correct ovsset object, but its json output is`["set",["foo"]]`, instead of `"foo"`

Right, but that's not wrong, is it? both encodings are valid IIUC. The current state of the PR is able to decode it correctly, but uses ["set", ["foo"]] as the default encoding way for all sets.

> The code is able to transfer a single value into Set, but I believe that this transformation should be done by Set itself. if somebody wants to work on the low-level API with Sets and Maps...
> 

The interesting aspect of the schema-based bindings is seen when decoding data from the DB, because it's able to know when "foo" really means []string{"foo"}.

> And without this PR, the `Empty_String_Set` produces `["set",null]` instead of `["set",[]]`, the same with Maps

I agree this PR is needed regardless of mine

**Comment by roytman** [comment]
> Right, but that's not wrong, is it? both encodings are valid IIUC. The current state of the PR is able to decode it correctly, but uses ["set", ["foo"]] as the default encoding way for all sets.

For the server-side encoding it can be an issue if existing clients assume to get a single value as "foo" and not ["set", ["foo"]] 

> The interesting aspect of the schema-based bindings is seen when decoding data from the DB, because it's able to know when "foo" really means []string{"foo"}.

I absolutely agree that schema-based binding helps to validate data, prevent errors, and simplifies development. I'm just wondering that the actual Set's json encoding and decoding should be done by Set itself. The schema binding decides that the next element should be a Set, and the Set decodes the element independently if it is an empty Set, a Set with several values, or a single element.

**Comment by amorenoz** [comment]
> > Right, but that's not wrong, is it? both encodings are valid IIUC. The current state of the PR is able to decode it correctly, but uses ["set", ["foo"]] as the default encoding way for all sets.
> 
> For the server-side encoding it can be an issue if existing clients assume to get a single value as "foo" and not ["set", ["foo"]]
> 

I would argue such client is not RFC-compliant since both modes are valid.
The way I read the RFC, it's really up to the implementation to decide the encoding format. I chose to default to the ["set", ["foo"]] format for two main reasons:
-  It's more "expressive" and it helped (myself) determine if the right type was selected looking at the raw data.
- Being a a specific case of the more generic encoding format I believe it's more likely that the other side will support it.

Apart from being slightly more compact, what benefits do you see on the other format?

> > The interesting aspect of the schema-based bindings is seen when decoding data from the DB, because it's able to know when "foo" really means []string{"foo"}.
> 
> I absolutely agree that schema-based binding helps to validate data, prevent errors, and simplifies development. I'm just wondering that the actual Set's json encoding and decoding should be done by Set itself. The schema binding decides that the next element should be a Set, and the Set decodes the element independently if it is an empty Set, a Set with several values, or a single element.

Good point. Then we need to change `NewOvsSet()` right?

**Comment by roytman** [comment]
> Then we need to change NewOvsSet() right?

Actuly I thought about 
`func (o *OvsSet) UnmarshalJSON(b []byte) (err error)`

**Comment by amorenoz** [comment]
I think all functions should accept single elements or it will force higher levels of code to transform "foo" -> []string{"foo"}

 @vtolstov @hzhou8 Any comments on which should be the default encoding for single elements?

**Comment by vtolstov** [comment]
i'm prefer to be RFC compliant if that possible and avoid any extremal optimizations that can break compatibility with public RFCs

**Comment by hzhou8** [comment]
> @vtolstov @hzhou8 Any comments on which should be the default encoding for single elements?

I think as long as it is RFC compliant it should be fine. I.e. I am fine with using "set" format for single element set encoding. (of course for decoding we should support both formats)

**Comment by hzhou8** [comment]
>     * In my fork I updated the `Set` marshal and unmarshal methods to provide OVSDB like behavior when the set contains a single entry. Can you consider including this functionality into the main stream ?
> 
Could you share your change (maybe just send a PR)?

>     * Currently, the libovsdb supports only types from RFC7047, do you have plans to extend it by the types/methods from  https://docs.openvswitch.org/en/latest/ref/ovsdb-server.7/.

Sorry I didn't see any types missing. Could you point it out?
For the other enhancement, such as monitor2/3 it is in the roadmap (for efficiency).

**Comment by hzhou8** [comment]
Thanks @roytman . The change LGTM, but it would be better to split the go.dep and go.sum changes into a separate commit (in this same PR).

@amorenoz @vtolstov any comments to this PR since you have reviewed?

**Comment by roytman** [comment]
@hzhou8, thanks for the review and comments. 

> it would be better to split the go.dep and go.sum changes into a separate commit (in this same PR).

Done.

**Comment by roytman** [comment]
> Sorry I didn't see any types missing. Could you point it out?

I meant for example `MonitorCondRequest` is is like `MonitorRequest`, but with the `Where` entry.
`RowUpdate2`  has a different format. 

I can submit a PR

**Comment by vtolstov** [comment]
i'm ok with this changes

**Review by vtolstov — APPROVED** [review]

**Comment by hzhou8** [comment]
> @hzhou8, thanks for the review and comments.
> 
> > it would be better to split the go.mod and go.sum changes into a separate commit (in this same PR).
> 
> Done.

@roytman , sorry that I wasn't clear enough. I didn't mean to split UT in separate commit. UT should always be involved in the same commit of the feature change, so that the commit is independently correct. What I meant was that I saw some dependency changes in go.mod/sum, and seems unrelated to the commit, such as: https://github.com/eBay/libovsdb/pull/32/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L9-L10

Not sure how was this dependency change generated. If it is unrelated, please split into a separate commit. But if you confirm the change is required for the same commit, I can just squash it and merge it.

**Comment by roytman** [comment]
The UTs use the `github.com/stretchr/testify` framework. So it was added to the go.mod, and so the UT and the go.mod modification are in the same commit. 
Other dependencies changes were done automatically.
If you're OK with the changes, please squash them.

**Pull request merged**
